Traceback (most recent call last):
  File "/Users/mt361/Desktop/RL-Bandits/train.py", line 55, in <module>
    algo.train()
  File "/Users/mt361/Desktop/RL-Bandits/algo.py", line 325, in train
    stats, envs, observations, prev_state = self.algo_step(
  File "/Users/mt361/Desktop/RL-Bandits/algo.py", line 226, in algo_step
    prob_t, prev_state = model(observations, prev_state) # get from actor network, prob_t is bsz x 1 x naction
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/mt361/Desktop/RL-Bandits/model.py", line 175, in forward
    Z = F.gelu(self.bn1(self.conv1(X.view(-1, self.iC, self.iH, self.iW))))
RuntimeError: shape '[-1, 3, 128, 128]' is invalid for input of size 806400